version: '3'

volumes:
  postgres_data:
    driver: local
  keycloak_postgres_data:
    driver: local

services:

  postgres:
    image: postgres
    env_file:
        - ./insureme/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}    

  keycloak-postgres:
      image: postgres
      env_file:
        - ./insureme/.env
      volumes:
        - keycloak_postgres_data:/var/lib/postgresql/data
      ports: 
        - 5433:5432
      environment:
        POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB}
        POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
        POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      env_file:
        - ./insureme/.env
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: keycloak-postgres
        DB_DATABASE: ${KEYCLOAK_POSTGRES_DB}
        DB_USER: ${KEYCLOAK_POSTGRES_USER}
        DB_SCHEMA: public
        DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
        KEYCLOAK_USER: ${KEYCLOAK_USER}
        KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 8080:8080
      depends_on:
        - keycloak-postgres